/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import clases.Metodos;
import com.toedter.calendar.JCalendar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static ventanas.TrabajoTerminado.fechaVencimientoG;
import static ventanas.TrabajoTerminado.txtFecha;

/**
 *
 * @author Luis
 */
public class ContratorGarantias extends javax.swing.JDialog {

    /**
     * Creates new form ContratorGarantias
     */
    public ContratorGarantias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jtDesde.setDate(new JCalendar().getDate());
        jtHasta.setDate(new JCalendar().getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtDesde = new com.toedter.calendar.JDateChooser();
        jtHasta = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jbExportar = new javax.swing.JButton();
        listaContratoGarant = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        buscar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Impresion de documentos");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Rango de Fechas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Monospaced", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Desde:");

        jtDesde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jtHasta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hasta:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Cliente", "Fecha de emision", "Fecha de vencimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalle.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDetalle);
        if (tablaDetalle.getColumnModel().getColumnCount() > 0) {
            tablaDetalle.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaDetalle.getColumnModel().getColumn(1).setPreferredWidth(250);
            tablaDetalle.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaDetalle.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jbExportar.setBackground(new java.awt.Color(69, 99, 123));
        jbExportar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jbExportar.setForeground(new java.awt.Color(255, 255, 255));
        jbExportar.setText("IMPRIMIR");

        listaContratoGarant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contrato", "Garantia", " ", " " }));
        listaContratoGarant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaContratoGarantItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel2.setText("Elija una opción");

        buscar_btn.setBackground(new java.awt.Color(69, 99, 123));
        buscar_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        buscar_btn.setForeground(new java.awt.Color(255, 255, 255));
        buscar_btn.setText("BUSCAR");
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaContratoGarant, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar_btn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExportar)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaContratoGarant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buscar_btn))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbExportar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaContratoGarantItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaContratoGarantItemStateChanged

    }//GEN-LAST:event_listaContratoGarantItemStateChanged

    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed
        if (listaContratoGarant.getSelectedIndex() == 0) {
            Conexion cn = new Conexion();
            try {
                cn.conectar();
                ResultSet pedi = cn.consultar("SELECT \n"
                        + "gc.id_garantia_cab,\n"
                        + "c.cli_nomb||' '||c.cli_apelli as nombre_cliente, \n"
                        + "gc.fecha_registro,\n"
                        + "gc.fecha_expiracion\n"
                        + "FROM garantia_cab gc\n"
                        + "JOIN cliente c\n"
                        + "ON gc.id_cliente = c.cli_cod\n"
                        + "WHERE gc.fecha_registro BETWEEN '" + Metodos.dameFechaFormateadaSQL(jtDesde.getDate()) +
                        "' and '" + Metodos.dameFechaFormateadaSQL(jtHasta.getDate()) + "' " //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final
                        + "ORDER BY id_garantia_cab;");
//            ResultSet pedi = cn.consultar("select * from pedido_venta where fecha BETWEEN '" + Metodos.dameFechaFormateadaSQL(jtDesde.getDate()) + "' and '" + Metodos.dameFechaFormateadaSQL(jtHasta.getDate()) + "' and estado !='ANULADO' order by cod_pedi_ven"); //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final
                Metodos.limpiarTabla(tablaDetalle);
                if (pedi.isBeforeFirst()) {
                    while (pedi.next()) {

                        Metodos.cargarTabla(tablaDetalle, new Object[]{
                            pedi.getString("id_garantia_cab"),
                            pedi.getString("nombre_cliente"),
                            pedi.getString("fecha_registro"),
                            pedi.getString("fecha_expiracion")});
                    }
                } else {

                    JOptionPane.showMessageDialog(null, "No hay registros en la base de datos");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(clientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se encuentra " + ex.getMessage());
            } catch (SQLException ex) {
                Logger.getLogger(clientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            Conexion cn = new Conexion();
            try {
                cn.conectar();
                ResultSet pedi = cn.consultar("SELECT\n"
                        + "cs.id_contrato,\n"
                        + "cs.fecha,\n"
                        + "c.cli_nomb||' '||c.cli_apelli as nombre_cliente\n"
                        + "FROM contrato_servicio_cab cs\n"
                        + "JOIN presupuesto_servicio_cabecera ps\n"
                        + "ON ps.id_presupuesto_reparacion_cab = id_presupuesto_rewparacion_cab\n"
                        + "JOIN cliente c\n"
                        + "ON c.cli_cod = cs.id_cliente\n"
                        + "WHERE cs.fecha BETWEEN '" + Metodos.dameFechaFormateadaSQL(jtDesde.getDate()) + 
                        "' and '" + Metodos.dameFechaFormateadaSQL(jtHasta.getDate()) + "';"); //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final
//            ResultSet pedi = cn.consultar("select * from pedido_venta where fecha BETWEEN '" + Metodos.dameFechaFormateadaSQL(jtDesde.getDate()) + "' and '" + Metodos.dameFechaFormateadaSQL(jtHasta.getDate()) + "' and estado !='ANULADO' order by cod_pedi_ven"); //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final
                Metodos.limpiarTabla(tablaDetalle);
                if (pedi.isBeforeFirst()) {
                    while (pedi.next()) {

                        Metodos.cargarTabla(tablaDetalle, new Object[]{
                            pedi.getString("id_contrato"),
                            pedi.getString("nombre_cliente"),
                            pedi.getString("fecha"),
                            "-"});
                    }
                } else {

                    JOptionPane.showMessageDialog(null, "No hay registros en la base de datos");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(clientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se encuentra " + ex.getMessage());
            } catch (SQLException ex) {
                Logger.getLogger(clientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_buscar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratorGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratorGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratorGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratorGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContratorGarantias dialog = new ContratorGarantias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbExportar;
    private com.toedter.calendar.JDateChooser jtDesde;
    private com.toedter.calendar.JDateChooser jtHasta;
    private javax.swing.JComboBox<String> listaContratoGarant;
    private javax.swing.JTable tablaDetalle;
    // End of variables declaration//GEN-END:variables
}
