/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;


import java.sql.*;
import Acceso.*;
import clases.Conexion;
import clases.reporteConexion;
import java.net.URL;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nestors
 */
public class llamadorReferenciales extends javax.swing.JFrame {
    
    

    /**
     * Creates new form llamador
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public llamadorReferenciales() throws ClassNotFoundException, SQLException {
        initComponents();   
        btn_cancelar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rbt_cursos = new javax.swing.JRadioButton();
        rbt_ciudad = new javax.swing.JRadioButton();
        btn_cancelar = new javax.swing.JButton();
        btn_seleccionar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rbt_marca = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rbt_materias = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rbt_bancos = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        rbt_cajas = new javax.swing.JRadioButton();
        rbt_actividad = new javax.swing.JRadioButton();
        rbt_alumnos = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rbt_formasCobros = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        rbt_funcionarios = new javax.swing.JRadioButton();
        rbt_clientes = new javax.swing.JRadioButton();
        rbt_cotizacion = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rbt_monedas = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        rbt_motivos = new javax.swing.JRadioButton();
        rbt_modelos = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        rbt_producto = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        rbt_profesor = new javax.swing.JRadioButton();
        rbt_perfiles = new javax.swing.JRadioButton();
        rbt_postulantes = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        rbt_tarjetas = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        rbt_usuario = new javax.swing.JRadioButton();
        rbt_requisito = new javax.swing.JRadioButton();
        rbt_sucursales = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        rbt_vehiculos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 36)); // NOI18N
        jLabel1.setText("Informes Referenciales");

        rbt_cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbt_cursosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_cursosMousePressed(evt);
            }
        });
        rbt_cursos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_cursosKeyPressed(evt);
            }
        });

        rbt_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_ciudadMousePressed(evt);
            }
        });
        rbt_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_ciudadActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_seleccionar.setText("Seleccionar");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });

        btn_ver.setText("Ver");
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Referenciales");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Cursos");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Ciudad");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Marca");

        rbt_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_marcaMousePressed(evt);
            }
        });
        rbt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_marcaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Materias");

        rbt_materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_materiasMousePressed(evt);
            }
        });
        rbt_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_materiasActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Alumnos");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Bancos");

        rbt_bancos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_bancosMousePressed(evt);
            }
        });
        rbt_bancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_bancosActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Cajas");

        rbt_cajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_cajasMousePressed(evt);
            }
        });
        rbt_cajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_cajasActionPerformed(evt);
            }
        });

        rbt_actividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbt_actividadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_actividadMousePressed(evt);
            }
        });
        rbt_actividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_actividadKeyPressed(evt);
            }
        });

        rbt_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_alumnosMousePressed(evt);
            }
        });
        rbt_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_alumnosActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Actividades");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Cotización");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Formas de Cobro");

        rbt_formasCobros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_formasCobrosMousePressed(evt);
            }
        });
        rbt_formasCobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_formasCobrosActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Funcionarios");

        rbt_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_funcionariosMousePressed(evt);
            }
        });
        rbt_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_funcionariosActionPerformed(evt);
            }
        });

        rbt_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbt_clientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_clientesMousePressed(evt);
            }
        });
        rbt_clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_clientesKeyPressed(evt);
            }
        });

        rbt_cotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_cotizacionMousePressed(evt);
            }
        });
        rbt_cotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_cotizacionActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Clientes");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Monedas");

        rbt_monedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_monedasMousePressed(evt);
            }
        });
        rbt_monedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_monedasActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Motivos");

        rbt_motivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_motivosMousePressed(evt);
            }
        });
        rbt_motivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_motivosActionPerformed(evt);
            }
        });

        rbt_modelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbt_modelosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_modelosMousePressed(evt);
            }
        });
        rbt_modelos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_modelosKeyPressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Modelos");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Postulantes");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Producto");

        rbt_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_productoMousePressed(evt);
            }
        });
        rbt_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_productoActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Profesores");

        rbt_profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_profesorMousePressed(evt);
            }
        });
        rbt_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_profesorActionPerformed(evt);
            }
        });

        rbt_perfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbt_perfilesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_perfilesMousePressed(evt);
            }
        });
        rbt_perfiles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_perfilesKeyPressed(evt);
            }
        });

        rbt_postulantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_postulantesMousePressed(evt);
            }
        });
        rbt_postulantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_postulantesActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Perfiles");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Sucursales");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Tarjetas");

        rbt_tarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_tarjetasMousePressed(evt);
            }
        });
        rbt_tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_tarjetasActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Usuarios");

        rbt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_usuarioMousePressed(evt);
            }
        });
        rbt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_usuarioActionPerformed(evt);
            }
        });

        rbt_requisito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbt_requisitoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_requisitoMousePressed(evt);
            }
        });
        rbt_requisito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_requisitoKeyPressed(evt);
            }
        });

        rbt_sucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_sucursalesMousePressed(evt);
            }
        });
        rbt_sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_sucursalesActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Requisitos");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Vehiculos");

        rbt_vehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbt_vehiculosMousePressed(evt);
            }
        });
        rbt_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_vehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(rbt_formasCobros)
                                        .addGap(93, 93, 93)
                                        .addComponent(rbt_funcionarios)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_modelos)
                                        .addGap(55, 55, 55)
                                        .addComponent(rbt_monedas)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_motivos)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_perfiles)
                                        .addGap(53, 53, 53)
                                        .addComponent(rbt_postulantes))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel31))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(599, 599, 599)
                                .addComponent(rbt_producto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_cursos)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_ciudad))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_marca))
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_materias))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rbt_actividad)
                                        .addGap(45, 45, 45)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_alumnos))
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_bancos))
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbt_cajas)
                                        .addGap(35, 35, 35)
                                        .addComponent(rbt_clientes)
                                        .addGap(49, 49, 49)
                                        .addComponent(rbt_cotizacion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel9)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(rbt_profesor)
                                .addGap(62, 62, 62)
                                .addComponent(rbt_requisito))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbt_sucursales)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbt_tarjetas)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbt_usuario)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(rbt_vehiculos)))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbt_cursos)
                            .addComponent(rbt_ciudad)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_marca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_materias))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbt_actividad)
                            .addComponent(rbt_alumnos)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_bancos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbt_cajas)
                            .addComponent(rbt_clientes)
                            .addComponent(rbt_cotizacion))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbt_formasCobros)
                                    .addComponent(rbt_funcionarios)
                                    .addComponent(rbt_modelos)
                                    .addComponent(rbt_monedas))
                                .addComponent(rbt_perfiles, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(rbt_postulantes)
                            .addComponent(rbt_producto)))
                    .addComponent(rbt_motivos))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbt_profesor)
                            .addComponent(rbt_requisito)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_sucursales))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_tarjetas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_usuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_vehiculos)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        btn_cancelar.setEnabled(false);
        btn_ver.setEnabled(false);
        btn_seleccionar.setEnabled(true);
        btn_salir.setEnabled(true);
        
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
        
        
        rbt_cursos.setSelected(false);
        rbt_ciudad.setSelected(false);
        rbt_marca.setSelected(false);
        rbt_materias.setSelected(false);
        rbt_actividad.setSelected(false);
        rbt_alumnos.setSelected(false);
        rbt_bancos.setSelected(false);
        rbt_cajas.setSelected(false);
        rbt_clientes.setSelected(false);
        rbt_cotizacion.setSelected(false);
        rbt_formasCobros.setSelected(false);
        rbt_funcionarios.setSelected(false);
        rbt_modelos.setSelected(false);
        rbt_monedas.setSelected(false);
        rbt_motivos.setSelected(false);
        rbt_perfiles.setSelected(false);
        rbt_postulantes.setSelected(false);
        rbt_producto.setSelected(false);
        rbt_profesor.setSelected(false);
        rbt_requisito.setSelected(false);
        rbt_sucursales.setSelected(false);
        rbt_tarjetas.setSelected(false);
        rbt_usuario.setSelected(false);
        rbt_vehiculos.setSelected(false);

        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        btn_cancelar.setEnabled(true);
        btn_ver.setEnabled(true);
        btn_salir.setEnabled(false);
        btn_seleccionar.setEnabled(false);
        
        rbt_cursos.setEnabled(true);
        rbt_ciudad.setEnabled(true);
        rbt_marca.setEnabled(true);
        rbt_materias.setEnabled(true);
        rbt_actividad.setEnabled(true);
        rbt_alumnos.setEnabled(true);
        rbt_bancos.setEnabled(true);
        rbt_cajas.setEnabled(true);
        rbt_clientes.setEnabled(true);
        rbt_cotizacion.setEnabled(true);
        rbt_formasCobros.setEnabled(true);
        rbt_funcionarios.setEnabled(true);
        rbt_modelos.setEnabled(true);
        rbt_monedas.setEnabled(true);
        rbt_motivos.setEnabled(true);
        rbt_perfiles.setEnabled(true);
        rbt_postulantes.setEnabled(true);
        rbt_producto.setEnabled(true);
        rbt_profesor.setEnabled(true);
        rbt_requisito.setEnabled(true);
        rbt_sucursales.setEnabled(true);
        rbt_tarjetas.setEnabled(true);
        rbt_usuario.setEnabled(true);
        rbt_vehiculos.setEnabled(true);

        
        
        
    }//GEN-LAST:event_btn_seleccionarActionPerformed

    private void rbt_cursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_cursosMouseClicked
        
        
    }//GEN-LAST:event_rbt_cursosMouseClicked

    private void rbt_cursosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_cursosKeyPressed
        
    }//GEN-LAST:event_rbt_cursosKeyPressed

    private void rbt_cursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_cursosMousePressed
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
        
    }//GEN-LAST:event_rbt_cursosMousePressed

    private void rbt_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_ciudadActionPerformed
        
    }//GEN-LAST:event_rbt_ciudadActionPerformed

    private void rbt_ciudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_ciudadMousePressed
        rbt_cursos.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);

    }//GEN-LAST:event_rbt_ciudadMousePressed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        btn_ver.setEnabled(false);
        enviarNombre();
//          generarReportes();    
    }//GEN-LAST:event_btn_verActionPerformed

    private void rbt_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_marcaMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_marcaMousePressed

    private void rbt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_marcaActionPerformed
        
    }//GEN-LAST:event_rbt_marcaActionPerformed

    private void rbt_materiasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_materiasMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_materiasMousePressed

    private void rbt_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_materiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_materiasActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void rbt_bancosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_bancosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_bancosMousePressed

    private void rbt_bancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_bancosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_bancosActionPerformed

    private void rbt_cajasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_cajasMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_cajasMousePressed

    private void rbt_cajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_cajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_cajasActionPerformed

    private void rbt_actividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_actividadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_actividadMouseClicked

    private void rbt_actividadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_actividadMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_actividadMousePressed

    private void rbt_actividadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_actividadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_actividadKeyPressed

    private void rbt_alumnosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_alumnosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_alumnosMousePressed

    private void rbt_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_alumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_alumnosActionPerformed

    private void rbt_formasCobrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_formasCobrosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_formasCobrosMousePressed

    private void rbt_formasCobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_formasCobrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_formasCobrosActionPerformed

    private void rbt_funcionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_funcionariosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_funcionariosMousePressed

    private void rbt_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_funcionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_funcionariosActionPerformed

    private void rbt_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_clientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_clientesMouseClicked

    private void rbt_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_clientesMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_clientesMousePressed

    private void rbt_clientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_clientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_clientesKeyPressed

    private void rbt_cotizacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_cotizacionMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_cotizacionMousePressed

    private void rbt_cotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_cotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_cotizacionActionPerformed

    private void rbt_monedasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_monedasMousePressed
         rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_monedasMousePressed

    private void rbt_monedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_monedasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_monedasActionPerformed

    private void rbt_motivosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_motivosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_motivosMousePressed

    private void rbt_motivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_motivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_motivosActionPerformed

    private void rbt_modelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_modelosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_modelosMouseClicked

    private void rbt_modelosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_modelosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_modelosMousePressed

    private void rbt_modelosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_modelosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_modelosKeyPressed

    private void rbt_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_productoMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_productoMousePressed

    private void rbt_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_productoActionPerformed

    private void rbt_profesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_profesorMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_profesorMousePressed

    private void rbt_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_profesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_profesorActionPerformed

    private void rbt_perfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_perfilesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_perfilesMouseClicked

    private void rbt_perfilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_perfilesMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_perfilesMousePressed

    private void rbt_perfilesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_perfilesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_perfilesKeyPressed

    private void rbt_postulantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_postulantesMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_postulantesMousePressed

    private void rbt_postulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_postulantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_postulantesActionPerformed

    private void rbt_tarjetasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_tarjetasMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_tarjetasMousePressed

    private void rbt_tarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_tarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_tarjetasActionPerformed

    private void rbt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_usuarioMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_usuarioMousePressed

    private void rbt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_usuarioActionPerformed

    private void rbt_requisitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_requisitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_requisitoMouseClicked

    private void rbt_requisitoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_requisitoMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_requisitoMousePressed

    private void rbt_requisitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_requisitoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_requisitoKeyPressed

    private void rbt_sucursalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_sucursalesMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
        rbt_vehiculos.setEnabled(false);
    }//GEN-LAST:event_rbt_sucursalesMousePressed

    private void rbt_sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_sucursalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_sucursalesActionPerformed

    private void rbt_vehiculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbt_vehiculosMousePressed
        rbt_cursos.setEnabled(false);
        rbt_ciudad.setEnabled(false);
        rbt_marca.setEnabled(false);
        rbt_materias.setEnabled(false);
        rbt_actividad.setEnabled(false);
        rbt_alumnos.setEnabled(false);
        rbt_bancos.setEnabled(false);
        rbt_cajas.setEnabled(false);
        rbt_clientes.setEnabled(false);
        rbt_cotizacion.setEnabled(false);
        rbt_formasCobros.setEnabled(false);
        rbt_funcionarios.setEnabled(false);
        rbt_modelos.setEnabled(false);
        rbt_monedas.setEnabled(false);
        rbt_motivos.setEnabled(false);
        rbt_perfiles.setEnabled(false);
        rbt_postulantes.setEnabled(false);
        rbt_producto.setEnabled(false);
        rbt_profesor.setEnabled(false);
        rbt_requisito.setEnabled(false);
        rbt_sucursales.setEnabled(false);
        rbt_tarjetas.setEnabled(false);
        rbt_usuario.setEnabled(false);
    }//GEN-LAST:event_rbt_vehiculosMousePressed

    private void rbt_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_vehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_vehiculosActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(llamadorReferenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(llamadorReferenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(llamadorReferenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(llamadorReferenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new llamadorReferenciales().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(llamadorReferenciales.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(llamadorReferenciales.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbt_actividad;
    private javax.swing.JRadioButton rbt_alumnos;
    private javax.swing.JRadioButton rbt_bancos;
    private javax.swing.JRadioButton rbt_cajas;
    private javax.swing.JRadioButton rbt_ciudad;
    private javax.swing.JRadioButton rbt_clientes;
    private javax.swing.JRadioButton rbt_cotizacion;
    private javax.swing.JRadioButton rbt_cursos;
    private javax.swing.JRadioButton rbt_formasCobros;
    private javax.swing.JRadioButton rbt_funcionarios;
    private javax.swing.JRadioButton rbt_marca;
    private javax.swing.JRadioButton rbt_materias;
    private javax.swing.JRadioButton rbt_modelos;
    private javax.swing.JRadioButton rbt_monedas;
    private javax.swing.JRadioButton rbt_motivos;
    private javax.swing.JRadioButton rbt_perfiles;
    private javax.swing.JRadioButton rbt_postulantes;
    private javax.swing.JRadioButton rbt_producto;
    private javax.swing.JRadioButton rbt_profesor;
    private javax.swing.JRadioButton rbt_requisito;
    private javax.swing.JRadioButton rbt_sucursales;
    private javax.swing.JRadioButton rbt_tarjetas;
    private javax.swing.JRadioButton rbt_usuario;
    private javax.swing.JRadioButton rbt_vehiculos;
    // End of variables declaration//GEN-END:variables

    public String enviarNombre(){
    if (rbt_cursos.isSelected()) {
        genreporte("reporteCursos.jasper", "select cur_cod, cur_desc from cursos");
    }else if (rbt_ciudad.isSelected()) {
        genreporte("reporteCiudad.jasper", "select ciu_cod, ciu_desc from ciudad");
    }else if (rbt_marca.isSelected()) {
        genreporte("reporteMarcas.jasper", "select mar_cod, mar_desc from marca");
    }else if (rbt_materias.isSelected()) {
        genreporte("reporteMaterias.jasper", "select mat_cod, mat_desc from materias");
    }else if (rbt_actividad.isSelected()) {
        genreporte("reporteActividad.jasper", "select acti_cod, acti_desc, acti_estado from actividad");
    }else if (rbt_alumnos.isSelected()) {
        genreporte("reporteAlumnos.jasper", "select alu_cod, alu_nomb, alu_apelli, alu_ci, alu_direcc, alu_telef, alu_ruc, alu_email, ciu_desc from v_alumnos");
    }else if (rbt_bancos.isSelected()) {
        genreporte("reporteBancos.jasper", "select ban_cod, ban_desc, ban_telef, ban_direcc from banco");
    }else if (rbt_cajas.isSelected()) {
        genreporte("reporteCajas.jasper", "select caja_cod, caja_desc from cajas");
    }else if (rbt_clientes.isSelected()) {
        genreporte("reporteClientes.jasper", "select cli_cod, cli_razonsocial, cli_ruc, cli_telef, cli_dire, ciu_desc from v_clientes");
    }else if (rbt_cotizacion.isSelected()) {
        genreporte("reporteCotizacion.jasper", "select coti_cod, mone_desc, coti_pre_compra, coti_pre_venta, coti_fecha, coti_hora from v_cotizacion;");
    }else if (rbt_formasCobros.isSelected()) {
        genreporte("reporteFormaCobro.jasper", "select cod_cob_tipo, cob_tipo_desc from cobro_forma");
    }else if (rbt_funcionarios.isSelected()) {
        genreporte("reporteFuncionarios.jasper", "select fun_cod, fun_nomb, fun_apelli, fun_ci, fun_dire, fun_telef, fun_ruc, fun_email, ciu_desc, suc_desc from v_funcionarios");
    }else if (rbt_modelos.isSelected()) {
        genreporte("reporteModelos.jasper", "select mod_cod, mod_desc from modelo");
    }else if (rbt_monedas.isSelected()) {
        genreporte("reporteMonedas.jasper", "select mone_cod, mone_desc from monedas");
    }else if (rbt_motivos.isSelected()) {
        genreporte("reporteMotivos.jasper", "select moti_cod, moti_desc, moti_tipo from motivos");
    }else if (rbt_perfiles.isSelected()) {
        genreporte("reportePerfiles.jasper", "select perfil_cod, perfil_desc from perfiles");
    }else if (rbt_postulantes.isSelected()) {
        genreporte("reportePostulantes.jasper", "select postu_cod, postu_nomb, postu_ape, postu_ci, postu_telef, postu_dire, postu_ruc, postu_email, ciu_desc from v_postulantes");
    }else if (rbt_producto.isSelected()) {
        genreporte("reporteProducto.jasper", "select pro_cod, pro_desc, pro_costo, pro_precio, pro_tipo_imp from producto;");
    }else if (rbt_profesor.isSelected()) {
        genreporte("reporteProfesores.jasper", "select prof_cod, prof_nomb, prof_apelli, prof_ci, prof_telef, prof_email, prof_ruc, ciu_desc from v_profes");
    }else if (rbt_requisito.isSelected()) {
        genreporte("reporteRequisitos.jasper", "select requi_cod, requi_desc from requisitos");
    }else if (rbt_sucursales.isSelected()) {
        genreporte("reporteSucursales.jasper", "select suc_cod, suc_desc, ciu_desc from v_sucursal");
    }else if (rbt_tarjetas.isSelected()) {
        genreporte("reporteTarjetas.jasper", "select tarj_cod, tarj_desc from tarjeta");
    }else if (rbt_usuario.isSelected()) {
        genreporte("reporteUsuarios.jasper", "select usu_cod, usu_alias, usu_estado, perfil_desc, sucursal, nombre from v_usuarios");
    }else if (rbt_vehiculos.isSelected()) {
        genreporte("reporteVehiculos.jasper", "select vehi_cod, vehi_desc, vehi_estado, mar_desc, mod_desc from v_vehiculos");
    }
    return "";
    
}

    public void genreporte(String nombre, String sql) {
        reporteConexion  conn = new reporteConexion();
        try{
            
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery(""+sql+"");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conn.resultado);
            
                   
            HashMap parameters = new HashMap();
            URL urlMaestro = getClass().getClassLoader().getResource("../reportes/"+nombre+"");

            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport, parameters, jrRS);
            JasperViewer ventana = new JasperViewer(masterPrint, false);
//            ventana.show();
            ventana.setTitle("Vista Previa");
            ventana.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(llamadorReferenciales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(llamadorReferenciales.class.getName()).log(Level.SEVERE, null, ex);
        }
}
 
//public void generarReportes(){
//    try {
//        JasperReport masterReport = null;
//        try {
//            masterReport = (JasperReport) JRLoader.loadObject(getClass().getResource("../reportes/"+enviarNombre()+""));
//            
//        } catch (JRException e) {
//            System.out.println("Error cargando el reporte maestro");
//        }
//        HashMap parameters = new HashMap();
//        JasperPrint jasperPrint = JasperFillManager.fillReport(masterReport, parameters, new Conexion().conectar());
//        JasperViewer jViewer = new JasperViewer(jasperPrint, true);
//        jViewer.setTitle("Reporte");
//        jViewer.setVisible(true);
//    } catch (Exception e) {
//        System.out.println("Error generando reporte : " + e.getMessage());
//    }
//}    
    

    
    
    
    
    
 
        
    
}
