/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Acceso.Menu;
import clases.Metodos;
import com.toedter.calendar.JCalendar;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class orden_produccion extends javax.swing.JFrame {

    public static int Bban;

//conexion conexion =new conexion();
    javax.swing.table.DefaultTableModel matriz;
    int resp = 0;
//  private Connection conn;
//
//    private ResultSet recur,rs;
//    String Buscar;
//    static String bd="produ";
//    static String login="root";
//    static String password="";
//    static String url="jdbc:mysql://localhost/" + bd;
    Statement snt;

    /**
     * Creates new form orden_produccion
     */
    public orden_produccion() {
        initComponents();

        this.setLocationRelativeTo(null);//centrar
        matriz = (javax.swing.table.DefaultTableModel) grilla.getModel();

        usuario.setText(Menu.empleado);
        sucursal.setText(Menu.Sucursal);
        nro_ord.setText(Metodos.siguienteCodigo("cod_or_prod", "orden_produccion"));
        fecha_dt.setDate(new JCalendar().getDate());
        Metodos.agregarClicDerechoATabla(grilla);
        Metodos.agregarClicDerechoATabla(grilla1);
        Metodos.agregarClicDerechoATabla(grilla2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        menu_productos = new javax.swing.JPopupMenu();
        eliminar = new javax.swing.JMenuItem();
        menu_materia_prima = new javax.swing.JPopupMenu();
        eliminar_materia = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nro_ord = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        codprodu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        desprod = new javax.swing.JTextField();
        cant = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nroorden = new javax.swing.JTextField();
        fecha_dt = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BAnular = new javax.swing.JButton();
        Bgrabar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        codprodu1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        desprod1 = new javax.swing.JTextField();
        cant1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grilla1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        nombre_personal_txt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cod_personal_txt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        etapa_txt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        grilla2 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        cod_equipo_txt = new javax.swing.JTextField();
        cod_etapa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        usuario = new javax.swing.JLabel();
        sucursal = new javax.swing.JLabel();
        inicio_dt = new com.toedter.calendar.JDateChooser();
        final_dt = new com.toedter.calendar.JDateChooser();
        agregar_equipo_btn = new javax.swing.JButton();

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        menu_productos.add(eliminar);

        eliminar_materia.setText("Eliminar");
        eliminar_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_materiaActionPerformed(evt);
            }
        });
        menu_materia_prima.add(eliminar_materia);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orden Produccion");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Orden produccion Nro.:");

        nro_ord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nro_ord.setEnabled(false);
        nro_ord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nro_ordActionPerformed(evt);
            }
        });
        nro_ord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nro_ordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nro_ordKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Fecha:");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Datos Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cod.:");

        codprodu.setEditable(false);
        codprodu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        codprodu.setEnabled(false);
        codprodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codproduActionPerformed(evt);
            }
        });
        codprodu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codproduKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codproduKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descripcion:");

        desprod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desprod.setEnabled(false);
        desprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desprodKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                desprodKeyTyped(evt);
            }
        });

        cant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cant.setEnabled(false);
        cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantActionPerformed(evt);
            }
        });
        cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cantidad:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("F2 BUSCADOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(codprodu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(desprod, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(codprodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(desprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel3.setBackground(new java.awt.Color(255, 51, 102));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Nro. Presu");

        nroorden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nroorden.setEnabled(false);
        nroorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroordenActionPerformed(evt);
            }
        });
        nroorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nroordenKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nroordenKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("Buscar (F2)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nroorden))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nro_ord, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(fecha_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nro_ord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(fecha_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nroorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        grilla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla.getTableHeader().setReorderingAllowed(false);
        grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                grillaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(grilla);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Equipo de trabajo");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Usuario:");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Sucursal:");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        BAnular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BAnular.setText("anular");
        BAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnularActionPerformed(evt);
            }
        });
        jPanel1.add(BAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        Bgrabar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bgrabar.setText("grabar");
        Bgrabar.setEnabled(false);
        Bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgrabarActionPerformed(evt);
            }
        });
        jPanel1.add(Bgrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("cancelar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 67, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("ORDEN DE PRODUCCIÓN");

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Datos Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cod.:");

        codprodu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        codprodu1.setEnabled(false);
        codprodu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codprodu1ActionPerformed(evt);
            }
        });
        codprodu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codprodu1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codprodu1KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Descripcion:");

        desprod1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desprod1.setEnabled(false);
        desprod1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desprod1KeyPressed(evt);
            }
        });

        cant1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cant1.setEnabled(false);
        cant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant1ActionPerformed(evt);
            }
        });
        cant1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cant1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cant1KeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cantidad:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("F2 BUSCADOR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(codprodu1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desprod1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cant1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(codprodu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(desprod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grilla1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grilla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla1.getTableHeader().setReorderingAllowed(false);
        grilla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grilla1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(grilla1);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Materiales a utilizar");

        nombre_personal_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nombre_personal_txt.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Personal");

        cod_personal_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cod_personal_txt.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Fecha de inicio");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Fecha final");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Etapa");

        etapa_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        etapa_txt.setEnabled(false);

        grilla2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grilla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fecha Inicio", "Fecha Final", "Personal", "Etapa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grilla2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(grilla2);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Codigo Equipo trabajo");

        cod_equipo_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cod_equipo_txt.setEnabled(false);

        cod_etapa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cod_etapa.setEnabled(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        usuario.setText("usuario");

        sucursal.setText("sucursal");

        inicio_dt.setDateFormatString("dd/MM/yyyy");

        final_dt.setDateFormatString("dd/MM/yyyy");

        agregar_equipo_btn.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cod_equipo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cod_personal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cod_etapa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(etapa_txt)
                                    .addComponent(nombre_personal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agregar_equipo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicio_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(final_dt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(sucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel8)
                    .addContainerGap(992, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(cod_equipo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20))
                                    .addComponent(inicio_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(final_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombre_personal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(cod_personal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(etapa_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cod_etapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregar_equipo_btn))
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel8)
                    .addContainerGap(628, Short.MAX_VALUE)))
        );

        jPanel4.getAccessibleContext().setAccessibleName("Datos Materiales");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnularActionPerformed
        ban = "anular";
//         jButton6.setEnabled(false);
        this.jButton4.setEnabled(true);
        this.jButton1.setEnabled(false);
        this.BAnular.setEnabled(false);
        this.Bgrabar.setEnabled(false);
        this.nro_ord.setEnabled(true);
        this.nro_ord.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_BAnularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ban = "nuevo";
        codprodu.setEnabled(true);
        nroorden.requestFocus();
        this.jButton4.setEnabled(true);
        this.jButton1.setEnabled(false);
        this.BAnular.setEnabled(false);
        this.Bgrabar.setEnabled(false);
        nroorden.setEnabled(true);
//    jButton6.setEnabled(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantKeyPressed
        if (evt.getKeyCode() == 10) {
            reemplazar();
            // presiona ENTER
            if (Integer.parseInt(cant.getText()) < 1) {
                JOptionPane.showMessageDialog(null, "La cantidad a cargar debe ser superior a 0 (CERO)", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                int subtotal;
                subtotal = Integer.parseInt(cant.getText());

                total = total + subtotal;
//          Letras.setText(numero.nletra(total));

                String registro[] = new String[]{codprodu.getText(), desprod.getText(), cant.getText(), String.valueOf(subtotal)};
                matriz.addRow(registro);
                limpiartext();
                cant.setEnabled(false);
                codprodu.setEnabled(true);
                codprodu.requestFocus();
            }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_cantKeyPressed

    private void codproduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codproduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codproduActionPerformed

    private void codproduKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codproduKeyPressed
//              if(evt.getKeyCode()==123) { // presiona F12
//            new bus_art(null,true).setVisible(true);// llama al buscador
//            
//            if (bus_art.vdes.isEmpty())//no trae nada
//            {
//                return;
//            }else // trae datos
//            {
//                codprodu.setText(bus_art.vcod);
//            }
//        }//fin F12

        if (evt.getKeyCode() == 35) { //35// presiona TECLA FIN
            Bgrabar.setEnabled(true);
            Bgrabar.requestFocus();
            // JOptionPane.showMessageDialog(null,"No puede Ingresar Letras!");
        }
//        if(evt.getKeyCode()==123) { // presiona F12
//        Bgrabar.setEnabled(true);
//            Bgrabar.requestFocus();
//        } // TODO add your handling code here:
    }//GEN-LAST:event_codproduKeyPressed

    private void BgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgrabarActionPerformed

        clear_text();
        limpiargrilla();
        des_text();
        jButton4.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_BgrabarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        des_text();
        clear_text();
//        jButton6.setEnabled(true);
        this.jButton4.setEnabled(false);
        this.BAnular.setEnabled(true);
        this.jButton1.setEnabled(true);
        this.Bgrabar.setEnabled(false);

        this.limpiargrilla();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantKeyTyped
        char caracter = evt.getKeyChar();
        int k = (int) evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (k != 10) && (caracter != KeyEvent.VK_BACK_SPACE)) {
//        JOptionPane.showMessageDialog(null,"No Puede Ingresar Letras");
            evt.consume();
        } else {
            if (k == 10) {
                if (cant.getText().equals("") == false) {

                    cant.setEnabled(true);
                    cant.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "No Puede Dejar El Campo Vacio");
                    cant.setText("");
                    cant.requestFocus();

                }

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cantKeyTyped

    private void grillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_grillaMouseClicked

    private void nro_ordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nro_ordKeyTyped
        char caracter = evt.getKeyChar();
        int k = (int) evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (k != 10) && (caracter != KeyEvent.VK_BACK_SPACE)) {
//            JOptionPane.showMessageDialog(null,"No Puede Ingresar Letras");
            evt.consume();
        } else {
            if (k == 10) {
                if (nro_ord.getText().equals("") == false) {

                    this.codprodu.setEnabled(true);
                    this.codprodu.requestFocus();
                    this.jButton4.setEnabled(true);
                    this.jButton1.setEnabled(false);
                    this.BAnular.setEnabled(false);
                    this.Bgrabar.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(null, "No Puede Dejar El Campo Vacio");
                    nro_ord.setText("");
                    nro_ord.requestFocus();

                }

            }
        }// TODO add your handling code here:
}//GEN-LAST:event_nro_ordKeyTyped

    private void nro_ordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nro_ordKeyPressed

}//GEN-LAST:event_nro_ordKeyPressed

    private void nro_ordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nro_ordActionPerformed

        // TODO add your handling code here:
}//GEN-LAST:event_nro_ordActionPerformed

    private void cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantActionPerformed
        // TODO add your handling code here:
        Metodos.cargarTabla(grilla, new Object[]{
            codprodu.getText(),
            desprod.getText(),
            cant.getText()
        });
    }//GEN-LAST:event_cantActionPerformed

    private void codproduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codproduKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        JOptionPane.showMessageDialog(null,"No puede Ingresar letras");
            codprodu.requestFocus();
        }
    }//GEN-LAST:event_codproduKeyTyped

    private void nroordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroordenActionPerformed

    }//GEN-LAST:event_nroordenActionPerformed

    private void nroordenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroordenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) { // presiona F2
            
            busPresupuestoProduccion.busqueda = "orden_produccion";
            new busPresupuestoProduccion().setVisible(true);
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!nroorden.getText().trim().isEmpty()){
                codprodu.setEnabled(true);
                desprod.setEnabled(true);
                cant.setEnabled(true);
                desprod.requestFocus();
                codprodu1.setEnabled(true);
                desprod1.setEnabled(true);
                cant1.setEnabled(true);
                habilitarEquipoTrabajo();
                cod_equipo_txt.setText(String.valueOf(Integer.parseInt(Metodos.ultimoCodigo("cod_equipo_trabajo", "equipo_de_trabajo"))+1));
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debes buscar un presupuesto de venta");
            }
        }
    }//GEN-LAST:event_nroordenKeyPressed

    private void nroordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroordenKeyTyped
        
    }//GEN-LAST:event_nroordenKeyTyped

    private void codprodu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codprodu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codprodu1ActionPerformed

    private void codprodu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codprodu1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codprodu1KeyPressed

    private void codprodu1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codprodu1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codprodu1KeyTyped

    private void cant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant1ActionPerformed

    private void cant1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cant1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) { 
            reemplazar();
            // presiona ENTER
            if (Integer.parseInt(cant1.getText()) < 1) {
                JOptionPane.showMessageDialog(null, "La cantidad a cargar debe ser superior a 0 (CERO)", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                int subtotal;
                subtotal = Integer.parseInt(cant1.getText());

                total = total + subtotal;
//          Letras.setText(numero.nletra(total));

                Object registro[] = new Object[]{codprodu1.getText(), desprod1.getText(), cant1.getText()};
                int fila = -1;
                for (int i = 0; i < grilla1.getRowCount(); i++) {
                   if(grilla1.getValueAt(i, 0).toString().equals(codprodu1.getText())){
                       fila = i;
                       break;
                   } 
                }
                
                if(fila == -1){
                    DefaultTableModel modelo = (DefaultTableModel) grilla1.getModel();
                    modelo.addRow(registro);
                }else{
                    int cantidad = Integer.parseInt(
                            grilla1.getValueAt(fila, 2).toString()) + Integer.parseInt(cant1.getText());
                    grilla1.setValueAt(cantidad, fila, 2);
                }
                limpiartext1();
                desprod1.requestFocus();
            }
        }
    }//GEN-LAST:event_cant1KeyPressed

    private void cant1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cant1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cant1KeyTyped

    private void grilla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grilla1MouseClicked
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            menu_materia_prima.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_grilla1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void grilla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grilla2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grilla2MouseClicked

    private void desprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desprodKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_desprodKeyTyped

    private void desprodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desprodKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F2){
            producto.operacion = "orden_produccion";
            new producto().setVisible(true);
            producto.operacion = "orden_produccion";
        }
    }//GEN-LAST:event_desprodKeyPressed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        Metodos.eliminarFila(grilla, grilla.getSelectedRow());
    }//GEN-LAST:event_eliminarActionPerformed

    private void grillaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            menu_productos.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_grillaMouseReleased

    private void desprod1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desprod1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F2){
            materiaPrima.busqueda = "orden_produccion";
            new materiaPrima().setVisible(true);
        }
    }//GEN-LAST:event_desprod1KeyPressed

    private void eliminar_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_materiaActionPerformed
        // TODO add your handling code here:
        Metodos.eliminarFila(grilla1, grilla1.getSelectedRow());
    }//GEN-LAST:event_eliminar_materiaActionPerformed

    /**
     * @param args the command line arguments orden_produccion ord_cod
     */
    private void limpiartext() {
        codprodu.setText("");
        cant.setText("");
        desprod.setText("");

        //un.setText("");
    }
    private void limpiartext1() {
        codprodu1.setText("");
        cant1.setText("");
        desprod1.setText("");

        //un.setText("");
    }
    
    private void habilitarEquipoTrabajo(){
        cod_equipo_txt.setEnabled(true);
        cod_personal_txt.setEnabled(true);
        nombre_personal_txt.setEnabled(true);
        cod_etapa.setEnabled(true);
        etapa_txt.setEnabled(true);
        inicio_dt.setDate(new JCalendar().getDate());
        final_dt.setDate(new JCalendar().getDate());
        
    }

    private void clear_text() {
        fecha_dt.setDate(new JCalendar().getDate());
        nro_ord.setText("");
        codprodu.setText("");

//    lcod.setText("");
//    lcod1.setText("");
//    Lnombre.setText("");
//    Lnombre.setText("");
//    fechainicio.setDate(null);
//    fechafinal.setDate(null);
    }

    private void des_text() {
        nro_ord.setEnabled(false);
        codprodu.setEnabled(false);
//          lcod.setEnabled(false);
//          lcod1.setEnabled(false);
//          Lnombre.setEnabled(false);
//          Lnombre1.setEnabled(false);
    }

    ///////////////////////
    private void limpiargrilla() {
        for (int i = grilla.getRowCount() - 1; i >= 0; i--) {
            matriz.removeRow(i);
        }
    }
    //////////////

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orden_produccion().setVisible(true);
            }
        });

    }

    private void salir() {
        int mensaje = JOptionPane.showConfirmDialog(this, "¿SALIR?", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    private String ban;
    public String iva = "";
    public ResultSet resu;
    public int total, totaliva5, totaliva10, totaliva, tocant, totales;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnular;
    private javax.swing.JButton Bgrabar;
    private javax.swing.JButton agregar_equipo_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    public static javax.swing.JTextField cant;
    public static javax.swing.JTextField cant1;
    private javax.swing.JTextField cod_equipo_txt;
    private javax.swing.JTextField cod_etapa;
    private javax.swing.JTextField cod_personal_txt;
    public static javax.swing.JTextField codprodu;
    public static javax.swing.JTextField codprodu1;
    public static javax.swing.JTextField desprod;
    public static javax.swing.JTextField desprod1;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JMenuItem eliminar_materia;
    private javax.swing.JTextField etapa_txt;
    private com.toedter.calendar.JDateChooser fecha_dt;
    private com.toedter.calendar.JDateChooser final_dt;
    public static javax.swing.JTable grilla;
    private javax.swing.JTable grilla1;
    private javax.swing.JTable grilla2;
    private com.toedter.calendar.JDateChooser inicio_dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu menu_materia_prima;
    private javax.swing.JPopupMenu menu_productos;
    private javax.swing.JTextField nombre_personal_txt;
    private javax.swing.JTextField nro_ord;
    public static javax.swing.JTextField nroorden;
    private javax.swing.JLabel sucursal;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

    public void reemplazar() {
        boolean encontro = false;
        for (int fila = 0; fila < grilla.getRowCount(); fila++) {
            if (codprodu.getText().equals(grilla.getValueAt(fila, 0).toString())) {
                encontro = true;
                matriz.removeRow(fila);
            }
        }
    }
    public String fecha_inicio = "";
    public String fechafin = "";

//     private void cargar_fechas()
//    {
//        try {
//
//            conn.sentencia = conn.conexion.createStatement();
//            conn.resultado = conn.sentencia.executeQuery("select curdate() as fecha ");
//            conn.resultado.next();
//               fechainicio.setDate(conn.resultado.getDate("fecha"));
//            fechafinal.setDate(conn.resultado.getDate("fecha"));
//        } //fin generar
//        catch (SQLException ex) {
//            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
//        }
//	
//}
//       private void verificar_fechaini()//throws ClassNotFoundException, InstantiationException, IllegalAccessException
//{
//                try
//                {
//                Calendar cal = Calendar.getInstance();
//                cal.setTime(fechainicio.getDate());
//                int dia = cal.get(Calendar.DAY_OF_MONTH);
//                int mes = cal.get(Calendar.MONTH) + 1;
//                String sdia = "";
//                String smes = "";
//                if (dia < 10)
//                {
//                    sdia = "0";
//                }
//                sdia += dia;
//                if (mes < 10)
//                {
//                    smes = "0";
//                }
//                smes += mes;
//                String fecha = cal.get(Calendar.YEAR) + "-" + smes + "-" + sdia;
//                fecha_inicio=fecha;
//               ver_conex conn =new ver_conex();
//                conn.sentencia = conn.conexion.createStatement();
//                conn.resultado = conn.sentencia.executeQuery("CALL verif_fecha ('"+fecha+"', CURDATE())");
//                boolean encontro = conn.resultado.next();
//                if (encontro == true)
//                {
//                                if (conn.resultado.getString("resul").equals("error"))
//                {
//                 JOptionPane.showMessageDialog(null, "LA FECHA INICIAL DEBE CORERSPONDER A ESTE AÑO","ATENCION", JOptionPane.WARNING_MESSAGE);
//                
//                }
//                 else
//              {
//                  
//                    
//                if (conn.resultado.getString("resul").equals("verdadero"))
//                {
//                 fechafinal.setEnabled(true);
//                 fechafinal.requestFocus();
//                fechainicio.setEnabled(false);
//                
//                } 
//                
//
//                else
//              {
//                JOptionPane.showMessageDialog(null, "LA FECHA INICIAL NO PUEDE SER MENOR A LA DE HOY","ATENCION", JOptionPane.WARNING_MESSAGE);
//                }
//                
//                }
//                }
//                else
//                {
//                JOptionPane.showMessageDialog(null, "NO ESTA VERIFICANDO","ATENCION", JOptionPane.INFORMATION_MESSAGE);
//                }
//                }
//                catch (SQLException ex)
//                {
//                    Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
//                }
//}
// private void verificar_fechafin()//throws ClassNotFoundException, InstantiationException, IllegalAccessException
//
// {
//          try
//            {
//                Calendar cal = Calendar.getInstance();
//                cal.setTime(fechafinal.getDate());
//                int dia = cal.get(Calendar.DAY_OF_MONTH);
//                int mes = cal.get(Calendar.MONTH) + 1;
//                String sdia = "";
//                String smes = "";
//                if (dia < 10)
//                {
//                    sdia = "0";
//                }
//                sdia += dia;
//                if (mes < 10)
//                {
//                    smes = "0";
//                }
//                smes += mes;                   
//                String fecha2 = cal.get(Calendar.YEAR) + "-" + smes + "-" + sdia;
//                fechafin=fecha2;
//               ver_conex conn =new ver_conex();
//                conn.sentencia = conn.conexion.createStatement();
//                conn.resultado = conn.sentencia.executeQuery("CALL verif_fecha ('"+fechafin+"', '"+fecha_inicio+"')");
//                boolean encontro = conn.resultado.next();
//                if (encontro == true)
//                {
//                    if (conn.resultado.getString("resul").equals("error"))
//                {
//                 JOptionPane.showMessageDialog(null, "LA FECHA FINAL DEBE CORERSPONDER A ESTE AÑO","ATENCION", JOptionPane.WARNING_MESSAGE);
//                
//                }
//                 else
//              {
//                  
//                    
//                if (conn.resultado.getString("resul").equals("verdadero"))
//                {
//                 codprodu.setEnabled(true);
//                 codprodu.requestFocus();
//                fechafinal.setEnabled(false);
//                
//                } 
//                
//
//                else
//              {
//                JOptionPane.showMessageDialog(null, "LA FECHA FINAL NO PUEDE SER MENOR A LA FECHA INICIAL","ATENCION", JOptionPane.WARNING_MESSAGE);
//                }
//                
//                }
//                   }
//                else
//                    {
//                JOptionPane.showMessageDialog(null, "NO ESTA VERIFICANDO","ATENCION", JOptionPane.INFORMATION_MESSAGE);
//                }
//            }
//         catch (SQLException ex)
//                {
//                    Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
//                }
}
