/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * produccion.java
 *
 * Created on 19/05/2013, 01:39:28 PM
 */
package ventanas;

import Acceso.Menu;
import clases.Conexion;
import clases.Metodos;
import com.toedter.calendar.JCalendar;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class produccion extends javax.swing.JFrame {

    public static int Bban;
//conexion conexion =new conexion();

    /**
     * Creates new form produccion
     */
    public produccion() {
        initComponents();
        usuario_lbl.setText(Menu.empleado);
        sucursal_lbl.setText(Menu.Sucursal);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nroorden = new javax.swing.JTextField();
        codproducc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtpro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();
        Materia2 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bgrabar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        observacion_txt = new javax.swing.JTextField();
        Materia3 = new javax.swing.JLabel();
        txtcant1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        grilla2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        grilla3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        fecha_dt = new com.toedter.calendar.JDateChooser();
        usuario_lbl = new javax.swing.JLabel();
        sucursal_lbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_deposito_txt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deposito_nombre_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produccion");

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Cantidad Realizada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla.setPreferredSize(new java.awt.Dimension(50, 224));
        grilla.getTableHeader().setReorderingAllowed(false);
        grilla.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                grillaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaMouseClicked(evt);
            }
        });
        grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                grillaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(grilla);

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nro. Orden:");

        nroorden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nroorden.setEnabled(false);
        nroorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroordenActionPerformed(evt);
            }
        });
        nroorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nroordenKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nroordenKeyTyped(evt);
            }
        });

        codproducc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        codproducc.setEnabled(false);
        codproducc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codproduccActionPerformed(evt);
            }
        });
        codproducc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codproduccKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Codigo:");

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Fecha:");

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("PRODUCCIÓN");

        jLabel13.setBackground(new java.awt.Color(0, 102, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Usuario:");

        jLabel14.setBackground(new java.awt.Color(0, 102, 102));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Sucursal:");

        txtpro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtpro.setEnabled(false);
        txtpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtproKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Nro. Producto :");

        descrip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        descrip.setEnabled(false);
        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        descrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripKeyTyped(evt);
            }
        });

        Materia2.setBackground(new java.awt.Color(0, 102, 102));
        Materia2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Materia2.setForeground(new java.awt.Color(0, 102, 102));
        Materia2.setText("Cantidad Realizada");

        txtcant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtcant.setEnabled(false);
        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        txtcant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("anular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        Bgrabar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bgrabar.setText("grabar");
        Bgrabar.setEnabled(false);
        Bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgrabarActionPerformed(evt);
            }
        });
        jPanel1.add(Bgrabar);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("cancelar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Observaciones");

        observacion_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        observacion_txt.setEnabled(false);
        observacion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observacion_txtActionPerformed(evt);
            }
        });

        Materia3.setBackground(new java.awt.Color(0, 102, 102));
        Materia3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Materia3.setForeground(new java.awt.Color(0, 102, 102));
        Materia3.setText("Cantidad Faltante");

        txtcant1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtcant1.setEnabled(false);
        txtcant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcant1ActionPerformed(evt);
            }
        });
        txtcant1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcant1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcant1KeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 418));

        grilla2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grilla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grilla2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(grilla2);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Materiales a utilizar");

        grilla3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grilla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fecha Inicio", "Fecha Final", "Personal", "Etapa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grilla3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(grilla3);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Equipo de trabajo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        usuario_lbl.setText("usuario");

        sucursal_lbl.setText("sucursal");

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("ID deposito");

        id_deposito_txt.setText("0");

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Deposito");

        deposito_nombre_lbl.setText("nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(codproducc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(nroorden, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fecha_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(observacion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(id_deposito_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addComponent(txtpro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(Materia2)
                                .addGap(10, 10, 10)
                                .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sucursal_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Materia3)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deposito_nombre_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuario_lbl)
                            .addComponent(sucursal_lbl))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codproducc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(fecha_dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(observacion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id_deposito_txt)
                    .addComponent(jLabel8)
                    .addComponent(deposito_nombre_lbl))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Materia2)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Materia3)
                    .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grillaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_grillaAncestorAdded
        // this.guardar.setEnabled(true); // TODO add your handling code here:
}//GEN-LAST:event_grillaAncestorAdded

    private void grillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grillaKeyPressed
        //   this.guardar.setEnabled(true);
        // TODO add your handling code here:
}//GEN-LAST:event_grillaKeyPressed

    private void BgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgrabarActionPerformed
        grabar();
}//GEN-LAST:event_BgrabarActionPerformed

    private void grabar() {
        System.out.println(ban);
        if (ban.equals("nuevo")) {
            System.out.println("hola");
            try {
                String produccion = "INSERT INTO produccion(\n"
                        + " cod_or_prod, fecha_pro, observacion, estado, \n"
                        + "usu_id, emp_id, sucur_id)\n"
                        + "VALUES ("
                        + nroorden.getText() + ", '"
                        + Metodos.dameFechaFormateadaSQL(fecha_dt.getDate()) + "', '"
                        + observacion_txt.getText() + "', "
                        + "'ACTIVO', "
                        + Menu.idUsuario + ", "
                        + Menu.idEmpleado + ", "
                        + Menu.idSucursal + ");";
                System.out.println(produccion);
                Conexion cn = new Conexion();
                cn.conectar();
                cn.actualizar(produccion);
                //guardamos el detalle
                
                int filas = grilla.getRowCount();
                for (int i = 0; i < filas; i++) {
                    
                    String detalle_pro = "INSERT INTO \"detalle_producción\"(\n"
                            + "\"cod_producción\", cod_or_prod, cod_depo, sucur_id, pro_cod, cantidad_realizada, \n"
                            + "cantidad_faltante)\n"
                            + "VALUES ("
                            + Metodos.ultimoCodigo("\"cod_producción\"", "produccion")+", "
                            + nroorden.getText()+", "
                            + id_deposito_txt.getText()+", "
                            + Menu.idSucursal+", "
                            + grilla.getValueAt(i, 0).toString()+", "
                            + grilla.getValueAt(i, 2).toString()+", "
                            + "0);";
                    cn.actualizar(detalle_pro);
                }

                JOptionPane.showMessageDialog(null, "Guardado Correctamente");
            } catch (SQLException ex) {
                Logger.getLogger(produccion.class.getName()).log(Level.SEVERE, null, ex);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(produccion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void codproduccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codproduccActionPerformed

}//GEN-LAST:event_codproduccActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ban = "nuevo";

//        BORR.setEnabled(true);
        this.jButton4.setEnabled(true);
        this.jButton1.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.Bgrabar.setEnabled(true);
        nroorden.setEnabled(true);
        nroorden.requestFocus();
        codproducc.setText(Metodos.siguienteCodigo("cod_or_prod", "produccion"));
        fecha_dt.setDate(new JCalendar().getDate());

//        this.nroorden.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nroordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroordenActionPerformed
        if (nroorden.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debes buscar un orden de produccion");
            return;
        }

        cargarProductos();
        cargarMateriaPrima();
        cargarEquipoTrabajo();

        observacion_txt.setEnabled(true);
        observacion_txt.requestFocus();


    }//GEN-LAST:event_nroordenActionPerformed

    private void nroordenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroordenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            busOrdenProduccion.busqueda = "produccion";
            new busOrdenProduccion().setVisible(true);
        }
    }//GEN-LAST:event_nroordenKeyPressed

    private void cargarProductos() {
        Conexion cn = new Conexion();

        try {
            cn.conectar();
            ResultSet producto = cn.consultar("SELECT\n"
                    + "p.pro_cod,\n"
                    + "p.pro_desc,\n"
                    + "dp.cantidad\n"
                    + "FROM detalle_orden_produccion dp\n"
                    + "JOIN producto p\n"
                    + "ON p.pro_cod = dp.pro_cod\n"
                    + "WHERE dp.cod_or_prod = " + nroorden.getText()); //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final

            Metodos.limpiarTabla(grilla);
            if (producto.isBeforeFirst()) {
                while (producto.next()) {
                    Metodos.cargarTabla(grilla, new Object[]{
                        producto.getInt("pro_cod"),
                        producto.getString("pro_desc"),
                        producto.getInt("cantidad")
                    });
                }
            }

            //cargamos la cabecera con los depositos
            String deposito = "SELECT \n"
                    + "dp.cod_depo,\n"
                    + "d.depo_desc\n"
                    + "FROM detalle_orden_produccion dp\n"
                    + "JOIN deposito d \n"
                    + "ON d.cod_depo =  dp.cod_depo\n"
                    + "WHERE dp.cod_or_prod = " + nroorden.getText() + " LIMIT 1";
            ResultSet deposito_rs = cn.consultar(deposito);
            if (deposito_rs.isBeforeFirst()) {
                while (deposito_rs.next()) {
                    id_deposito_txt.setText(String.valueOf(deposito_rs.getInt("cod_depo")));
                    deposito_nombre_lbl.setText(deposito_rs.getString("depo_desc"));
                }
            }

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarMateriaPrima() {
        Conexion cn = new Conexion();

        try {
            cn.conectar();
            ResultSet producto = cn.consultar("SELECT\n"
                    + "mu.cod_materia,\n"
                    + "m.mat_desc,\n"
                    + "mu.cantidad\n"
                    + "FROM materiales_a_utilizar mu\n"
                    + "JOIN materia_prima m\n"
                    + "ON m.cod_materia = mu.cod_materia\n"
                    + "WHERE mu.cod_or_prod =  " + nroorden.getText()); //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final

            Metodos.limpiarTabla(grilla2);
            if (producto.isBeforeFirst()) {
                while (producto.next()) {
                    Metodos.cargarTabla(grilla2, new Object[]{
                        producto.getInt("cod_materia"),
                        producto.getString("mat_desc"),
                        producto.getInt("cantidad")
                    });
                }
            }
        } catch (ClassNotFoundException ex) {

            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarEquipoTrabajo() {
        Conexion cn = new Conexion();

        try {
            cn.conectar();
            ResultSet producto = cn.consultar("SELECT\n"
                    + "dt.cod_equipo_trabajo,\n"
                    + "et.fecha_inicio,\n"
                    + "et.fecha_final,\n"
                    + "e.emp_nom||' '||e.emp_ape as personal,\n"
                    + "ep.eta_desc\n"
                    + "\n"
                    + "FROM detalle_equipo_trabajo dt\n"
                    + "JOIN empleado e\n"
                    + "ON e.emp_id = dt.emp_id\n"
                    + "JOIN equipo_de_trabajo et\n"
                    + "ON et.cod_equipo_trabajo = dt.cod_equipo_trabajo\n"
                    + "JOIN etapas_produccion ep\n"
                    + "ON ep.cod_etapas = dt.cod_etapas\n"
                    + "\n"
                    + "WHERE dt.cod_or_prod =" + nroorden.getText()); //order by ordena de menor a mayor, si se quiere de mayor a menor se le agrega desc al final

            Metodos.limpiarTabla(grilla3);
            if (producto.isBeforeFirst()) {
                while (producto.next()) {
                    Metodos.cargarTabla(grilla3, new Object[]{
                        producto.getInt("cod_equipo_trabajo"),
                        Metodos.dameFechaFormateada(producto.getDate("fecha_inicio")),
                        Metodos.dameFechaFormateada(producto.getDate("fecha_final")),
                        producto.getString("personal"),
                        producto.getString("eta_desc")
                    });
                }
            }
        } catch (ClassNotFoundException ex) {

            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(orden_produccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void nroordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroordenKeyTyped
        char caracter = evt.getKeyChar();
        int k = (int) evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (k != 10) && (caracter != KeyEvent.VK_BACK_SPACE)) {
//            JOptionPane.showMessageDialog(null, "No Puede Ingresar Letras");
            evt.consume();
        } else {
            if (k == 10) {
                if (nroorden.getText().equals("") == false) {

                    nroorden.setEnabled(true);
                    nroorden.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "No Puede Dejar El Campo Vacio");
                    nroorden.setText("");
                    nroorden.requestFocus();

                }

            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_nroordenKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void codproduccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codproduccKeyTyped

    }//GEN-LAST:event_codproduccKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ban = "anular";
        this.jButton4.setEnabled(true);
        this.jButton1.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.Bgrabar.setEnabled(false);
        this.codproducc.setEnabled(true);
        this.codproducc.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void grillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseClicked
//        this.BORR.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_grillaMouseClicked

    private void txtproKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproKeyPressed

        if (evt.getKeyCode() == 10) {
            Bban = 1;

            if (txtpro.getText().equals("") == false) {

            } else {
                //buscador
                JTextField[] tfParam = new JTextField[2];
                tfParam[0] = this.txtpro;

                String sql = "SELECT a.ide_producto, a.prod_descri AS articulo, a.prod_precio_costo AS precio FROM producto AS a, stock_producto AS tp WHERE a.ide_producto=tp.ide_producto AND a.ide_producto AND a.prod_descri like";

            }
            txtcant.setEnabled(true);
            txtcant.requestFocus();

        }
        if (evt.getKeyCode() == 17) {

        }
        if (evt.getKeyCode() == 35) {

            Bgrabar.setEnabled(true);

        }


    }//GEN-LAST:event_txtproKeyPressed

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripActionPerformed

    private void descripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripKeyPressed

    private void descripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_descripKeyTyped

    private void txtcantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantKeyPressed
        if (evt.getKeyCode() == 10) {
            if (txtcant.getText().equals("") == false) {

                for (int a = 0; a < grilla.getRowCount(); a++) {
                    // Object cod    =grilla.getValueAt(a,0);

                    if (txtpro.getText().equals(grilla.getValueAt(a, 0).toString())) {

                    }
                }

                String registro[] = new String[]{txtpro.getText(), descrip.getText(), txtcant.getText()};

                txtcant.setEnabled(false);
                txtpro.setEnabled(true);
                txtpro.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "No Puede Dejar El Campo Vacio");
                txtpro.requestFocus();
            }

        }
    }//GEN-LAST:event_txtcantKeyPressed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void txtcantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantKeyTyped


    }//GEN-LAST:event_txtcantKeyTyped

    private void observacion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observacion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observacion_txtActionPerformed

    private void txtcant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcant1ActionPerformed

    private void txtcant1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcant1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcant1KeyPressed

    private void txtcant1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcant1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcant1KeyTyped

    private void grilla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grilla2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grilla2MouseClicked

    private void grilla3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grilla3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grilla3MouseClicked
////////////////////////////////////////////////////////

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new produccion().setVisible(true);
            }
        });
    }

    private String ban;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bgrabar;
    private javax.swing.JLabel Materia2;
    private javax.swing.JLabel Materia3;
    private javax.swing.JTextField codproducc;
    public static javax.swing.JLabel deposito_nombre_lbl;
    private javax.swing.JTextField descrip;
    private com.toedter.calendar.JDateChooser fecha_dt;
    private javax.swing.JTable grilla;
    private javax.swing.JTable grilla2;
    private javax.swing.JTable grilla3;
    public static javax.swing.JLabel id_deposito_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextField nroorden;
    private javax.swing.JTextField observacion_txt;
    private javax.swing.JLabel sucursal_lbl;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtcant1;
    private javax.swing.JTextField txtpro;
    private javax.swing.JLabel usuario_lbl;
    // End of variables declaration//GEN-END:variables

    public int pe, pee;

}
